title: Learning Center
description: Learning Center!
baseurl: ""
url: 'http://lc.incubator.edurt.io'
permalink: /:categories/:title

content_type: Learning Center
use_authors: true

brand_logo: 
brand_name: Learning Center
header: How can we help you?
subheader: 感谢各位贡献者辛苦贡献的文章

meta_image: odin-meta.png

# Social Links
twitter_username: 
facebook_page:
github_username: EdurtIO
email: shicheng@ttxit.com
linkedin_page:
instagram_username: 

# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/EdurtIO

nav_item_two: 
nav_item_two_link: 

nav_item_three: #
nav_item_three_link: #

nav_button: GitHub
nav_button_link: https://github.com/EdurtIO

# More Help
help_one_title: 
help_one_content: 
help_one_button: 
help_one_link: 

help_two_title: 
help_two_content: 
help_two_button: 
help_two_link: 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

sass:
  sass_dir:          _scss
  style:            :compressed
