name: Publish docs via GitHub Pages
on: push

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: lc.incubator.edurt.io
          CONFIG_FILE: ./mkdocs.yml
          EXTRA_PACKAGES: build-base
